<a href="https://colab.research.google.com/github/AstraLucy/SkinSight/blob/main/skinsight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Testing Model

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.19.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.2722723 , -0.02652267, -0.16601202, -0.5629397 ,  0.4598228 ,
        -0.19394346, -0.23626736,  0.29029644, -0.20748636,  0.03830742]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.07985722, 0.10210379, 0.08881012, 0.05971438, 0.16605772,
        0.08636385, 0.08278487, 0.14016344, 0.08520211, 0.10894248]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.449186)

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.9151 - loss: 0.2938
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9564 - loss: 0.1433
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9669 - loss: 0.1069
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9732 - loss: 0.0869
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9774 - loss: 0.0736


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9773 - loss: 0.0751


[0.0751342847943306, 0.9772999882698059]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[9.8999379e-08, 2.4481453e-08, 1.0154436e-05, 1.2696332e-04,
        1.0848819e-11, 4.4712166e-07, 5.1883826e-15, 9.9985373e-01,
        2.0381387e-07, 8.3906780e-06],
       [6.4117977e-08, 7.1448470e-03, 9.9280375e-01, 1.0567780e-05,
        1.4694310e-15, 4.0171315e-05, 1.0338341e-08, 6.6948440e-11,
        6.0304109e-07, 9.4289340e-11],
       [6.4944487e-08, 9.9944240e-01, 2.1350499e-05, 8.1596755e-07,
        4.5300421e-05, 6.5969891e-07, 3.9482516e-06, 4.1727730e-04,
        6.6861823e-05, 1.2437797e-06],
       [9.9955350e-01, 3.3314599e-08, 8.3118211e-05, 1.3451185e-07,
        3.2861490e-07, 3.7743114e-06, 2.6347434e-06, 3.3710003e-04,
        2.9698131e-07, 1.9032217e-05],
       [1.7674429e-06, 4.4498580e-07, 5.0225649e-06, 3.5632661e-07,
        9.9801707e-01, 3.8341412e-07, 1.5164228e-05, 1.1829894e-04,
        8.5347489e-07, 1.8406064e-03]], dtype=float32)>

# Skin Sight Model